### ISSUE TITLE
Trouble running on OSX 10.10

### ISSUE THREAD

**Issue by richb-hanover** [jvns/neural-nets-are-weird#1]
*UPDATE: Solved - See: https://github.com/jvns/neural-nets-are-weird/issues/1#issuecomment-167808037*

Thanks for taking the time to post this container/tutorial.

I'm using OSX 10.10.5, and can (seemingly) install Docker from docker.com successfully. That is, I can run the "hello world" container and get the expected output. 

I then run the `docker build` command as shown on your main page, and the caffe container seems to build and be ready. 

I have trouble with the next step. I see the following in Terminal:

    bash-3.2$ docker run -i -p 9990:8888 -v $PWD:/neural-nets -t neural-nets-fun:caffe /bin/bash -c 'export     PYTHONPATH=/opt/caffe/python && cd /neural-nets && ipython notebook --no-browser --ip 0.0.0.0'
    [I 03:31:48.502 NotebookApp] Writing notebook server cookie secret to /.local/share/jupyter/runtime/notebook_cookie_secret
    [I 03:31:48.560 NotebookApp] Serving notebooks from local directory: /neural-nets
    [I 03:31:48.560 NotebookApp] 0 active kernels
    [I 03:31:48.561 NotebookApp] The IPython Notebook is running at: http://0.0.0.0:8888/
    [I 03:31:48.561 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

However, when I go to my web browser to connect to http://0.0.0.0:8888/ or localhost:8888, I can't connect, and see ERR_CONNECTION_REFUSED in Chrome. Further debugging:

* netstat does not show that either port 9990 or 8888 are open
* changing the invocation to use "localhost" instead of "0.0.0.0" doesn't help
* the terminal shows "0 active kernels" - does this mean anything?
* running the following command ````docker run -i -p 9990:8888 -v $PWD:/neural-nets -t neural-nets-fun:caffe```` gives me a root shell in the terminal.

Any ideas what could be wrong/what I can do to get on the air? Thanks!

**Comment by cfiorelli** [comment]
On using Chrome I read someplace that using Chrome would soon/if not already be losing support.
- using another browser may solve?

I'm setting this up in EC2 Ubuntu right now to get around the untested OSX situation, if that's useful.

Cheers

**Comment by richb-hanover** [comment]
@cfiorelli - I'd be interested to hear how how you make out. What do you get if you run this in your EC2 Ubuntu?

netstat | grep 9990
*and*
netstat | grep 8888

**Comment by DEKHTIARJonathan** [comment]
You should try visiting : http://localhost:9990 and not 8888. That's basic port forwarding ;)

Else you should look at the IP Address of your docker machine (do a simple ifconfig) and then : http://DockerMachineIP:9990

Cheers ;)

**Comment by cfiorelli** [comment]
+1 on port forwarding. 

last i checked the docker build in ec2 dropped:
  virtual memory exhausted: Cannot allocate memory

**Comment by DEKHTIARJonathan** [comment]
If you need a good build you can execute : 
docker pull born2data/caffecv

I have built it for you guys ;) Perfectly running !

https://hub.docker.com/r/born2data/caffecv/

**Comment by richb-hanover** [comment]
@DEKHTIARJonathan - I did try http://localhost:9990 as well. Both port 9990 and port 8888 give the same (no-response) results my OSX box. Two questions:

- Do you have it working on OSX? What version (10.?)
- What do you get when you run a netstat? (See my question from yesterday for the exact commands.)

**Comment by DEKHTIARJonathan** [comment]
@richb-hanover yes sir. I use Mac OS X.
Your problem is not related to this this git-repo, but "Docker related". Have you ever used it before ?

Let's try this : 
In the docker machine shell (not OSX shell) type "ifconfig", you will get the VM IP address.

Then use : http://IPaddress:9990

You need to test and tweak the network parameters of the docker VM.

If you're still doubting about this repo, you can pull the following dock and try with it :

docker pull bitnami/apache
docker run -d --name apacheTest -p 80:80 bitnami/apache

Then visit : http://localhost or http://IPaddress

You will get the famous "It Works" displayed.

**Comment by richb-hanover** [comment]
@DEKHTIARJonathan Thanks for the response. I have not used Docker before (I thought this would be a fun intro to the package). I agree with you that it's not a problem with this docker image, but with my docker installation. Further observations:

- I did the same install on a Ubuntu VM. Works as documented, except with http://localhost:9990
- I did attempt to log into the docker machine shell of the caffe container, but ifconfig is not installed (neither is netstat)
- I did run your bitnami/apache test. http://localhost did not work... However, I used the IP address shown by the docker start.sh script (http://192.168.99.100 on my machine) and got Apache's "It works" page. 

That's the clue! It appears that on OSX, you need to enter ````http://docker-address:9990```` into your browser, where *docker-address* is the IP address displayed by the docker startup script (e.g. 192.168.99.100 in the "screen shot" below):

````
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/


docker is configured to use the default machine with IP 192.168.99.100
````
Thanks for your help!

**Comment by richb-hanover** [comment]
Re-opening so that others can see the answer.

**Comment by DEKHTIARJonathan** [comment]
@richb-hanover  you're welcome ;)

**Comment by richb-hanover** [comment]
OK. You're right. I raised another issue, to point out that it's a problem in the documentation.
