### ISSUE TITLE
Failed to fetch http://........ Size mismatch

### ISSUE THREAD

**Issue by craftlk** [jvns/neural-nets-are-weird#10]
Get:231 http://http.debian.net/debian/ wheezy/main libsnappy-dev amd64 1.0.5-2 [38.0 kB]

Failed to fetch http://http.debian.net/debian/pool/main/libu/libunistring/libunistring0_0.9.3-5_amd64.deb  Size mismatch
Failed to fetch http://http.debian.net/debian/pool/main/x/x11proto-kb/x11proto-kb-dev_1.0.6-2_all.deb  Size mismatch
Failed to fetch http://http.debian.net/debian/pool/main/o/opencv/libopencv-objdetect2.3_2.3.1-11+deb7u1_amd64.deb  Error reading from server. Remote end closed connection [IP: 5.153.231.35 80]
Fetched 113 MB in 7min 51s (240 kB/s)
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c apt-get -y --force-yes install libprotobuf-dev libleveldb-dev libsnappy-dev libopencv-dev libhdf5-serial-dev protobuf-compiler' returned a non-zero code: 100

**Comment by DEKHTIARJonathan** [comment]
Hi,

Thanks not to call your issues "Big Problem". It doesn't help at all to answer you.

BTW. It's a debian apt failure you just need to try again.

The solution is explain here : https://github.com/jvns/neural-nets-are-weird/issues/9

**Comment by craftlk** [comment]
Thank you very much,I've found the link "http://dekhtiarjonathan.github.io/neural-nets-are-weird/http.html"
and try the "download" way,it worked well. 
PS:there's a small mistake:
(1) docker pull born2data/caffecv:http  
(2) docker run -it -p 9990:9990 -v $PWD:/neural-nets born2data:caffecv:http /bin/bash -c 'export PYTHONPATH=/opt/caffe/python && cd /neural-nets && ipython notebook --no-browser --ip 0.0.0.0 --port=9990'
In (2) ,it should be "born2data/caffecv:http"

**Comment by DEKHTIARJonathan** [comment]
@craftlk you're right, I will correct it ;) You can close the issue btw.

@jvns, as you can see my "two branches (https/http) and the documentation branch could be useful sometimes ;)
