### ISSUE TITLE
Var not defined in one cell

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [jvns/neural-nets-are-weird#2]
Hi,

I tried to fix this bug, but didn't find it ;)

Cell containing : 
## Step 1: the black screen
black = np.zeros_like(grad)
_ = predict(black, n_preds=5)

The var "grad" is not defined, I see how you compute it (with the function below), but what you use in input of the function ?

Please fix the notebook ;)

Thanks a lot for your awesome work.

**Comment by jvns** [comment]
oops, thanks! Will fix.

**Comment by jvns** [comment]
I pushed an update notebook. Try it now?

**Comment by DEKHTIARJonathan** [comment]
Fixed
