### ISSUE TITLE
Wrong address/wrong port in documentation

### ISSUE THREAD

**Issue by richb-hanover** [jvns/neural-nets-are-weird#5]
The instructions displayed by the neural-nets-fun:caffe container give the wrong address and port on some OS's.

**On Linux** use port 9990 - http://0.0.0.0:9990 in your browser (tested on Ubuntu 14.04.3)

**On OSX** use the docker-machine address and port 9990 - http://docker-machine:9990 where *docker-address* is the IP address displayed by the docker startup script (e.g. 192.168.99.100 in the "screen shot" below). (Tested on OSX 10.10.5)
````
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/

docker is configured to use the default machine with IP 192.168.99.100
````

**Comment by DEKHTIARJonathan** [comment]
Ok I'll need to re-explain ... It's not at all an issue ... It's just "basic docker networking".

It's not at all OS-based, it's config based.

## Docker Architecture

Docker is in between an hypervisor and a classic software. It makes "VM" running inside the host. (Look at Docker website for more details, my summary is really brief and quite inexact.)

Moreover, it's definitely a linux based software, only Linux system, at the moment, can run Docker.

## How do I contact my "Docker-VMs" ?

Inside your host you will use : http://localhost:VMPORT or whatever else protocol.
Outside the host : http://MachineHostingDockerIP:VMPORT

That's it.

## What if I use Mac OS or Windows ? Can I use Docker ?

Of course you can, but you need to create a Linux Based VM with VMware or VBox or whatever else and inside that machine you run Docker and your DockerVMs.

In order the access the services you need to use the instruction written in the previous point :
Outside the host : http://MachineHostingDockerIP:VMPORT

## Conclusion

The localhost thing work ONLY if you contact the DockerVMs from the machine running Docker, else it makes no sense !
So you can close this "issue" too, by default with Docker, we assume people run Docker locally (which is not your case, you need a VM). We can't explain every situation dude ;)

Keep it up with Docker, it's an awesome platform !

**Comment by richb-hanover** [comment]
What a great exposition! Thanks for all that background information - it does help clarify some of the layering.

Nonetheless, I think there are two things wrong with the current documentation:

1. The documentation says to use port 8888 in some places. I have never succeeded with that port, but it works every time with port 9990.

2. (Gettin' a little philosophical here...) This "Neural Networks are Weird" project/repo provides a "learning about neural networks" platform. The container is a **great** service for letting people play around with an important technology. It's a major triumph because it hides a really messy, gnarly installation (that jvns said required six hours of cursing) into an (almost) "fire and forget" process. 

But if I only wanted to horse around with neural networks, I would have concluded "This project doesn't work".

I have created a pull request to update the README.md file with instructions for OSX. (See https://github.com/richb-hanover/neural-nets-are-weird/pull/1 ) That would have allowed me to move along and actually play around with the neural net. Thanks again!

**Comment by DEKHTIARJonathan** [comment]
@richb-hanover  OK ... I did forgot one point my bad ...

When you create a VM docker based, application use "specific ports".

Let's say PostgreSQL which runs on port 5432, how do you do without changing the VM to run 4 PostgreSQL VMs docker based ? You simply can't without port mapping. Because if you contact the host, it won't know which of the PostgresVM you try to contact.

So they have implemented a simply trick : Port Mapping.

Lets say When you contact the host you have the following mapping :
** 10000 => 5432 VM1
** 10001 => 5432 VM2
** 10002 => 5432 VM3
** 10003 => 5432 VM4

Every Postgres VM runs on port 5432, however the host listen on 10000-10004 and redistribute according to the mapping.

The mapping is built inside the "docker run ..." command with the option : -p HostPort:VMPort

To conclude it's 1000% normal that you can't contact the VM on port 8888 because it has been mapped to 9990.

Again this is a basic Docker knowledge, you definetely need to investigate this part

**Comment by DEKHTIARJonathan** [comment]
BTW. I just look to your fork. I don't really agree for your changes (last part where you split : Linux / OS X).

It's project about Neural Nets, not about Docker, we shouldn't add extra platform-specific information.
As I said "Docker assume you run it locally", if you don't, you just adapt what's written. You can't make one bullet point for everything (Linux, WIndows, Mac OS, Amazon AWS, Google Cloud, Amazon Azure ...). If people have some trouble, they ask as you did, or look for some basic knowledge about Docker in Google (or whatever else).

**Comment by richb-hanover** [comment]
I think we're going to have to agree to disagree. (And let @jvns decide what to do.)

But first, an anecdote. In another life, I developed commercial software. People would download our demo, and if they liked it, they would buy. But we came to understand an important rule about demos:

*Every hiccup (even a tiny one) that stands in someone's way cuts in half the number of people who use it. And two hurdles == one-quarter the response, etc.*

I had been curious about neural networks for a long time, and the article on recurse.com made it sound as if I could simply download and get started. It was almost true - the packaging was spectacularly easy to use.

I downloaded, failed at that point, and was close to giving up. But I'm an obsessive compulsive computer guy, so I spent ~6+ hours googling, reading docs, learning about Docker and IPython, and experimenting to get to the point that it worked on my Mac. That effort pretty much uses up my "computer play time" for the next week or two.

So I *did* learn about Docker - and thanks for your very helpful explanations. As a techie, it's good to know about this tool. (Do you blog? You should write up your explanation - it's quite good). 

But I failed to learn anything about neural networks. That's why I want to include the hint about running on OSX.

**Comment by jvns** [comment]
@richb-hanover hey i'm really sad that it took you so much time to figure this out! Thank you so much for contributing a fix. Not having OS X instructions was something I was sad about.

I've merged your changes and they're now in the README at https://github.com/jvns/neural-nets-are-weird

**Comment by jvns** [comment]
I used docker to make it easier to get started, not to get in anyone's way. I don't want you to have to learn everything about Docker.

**Comment by richb-hanover** [comment]
Thanks for merging my changes. You did a great job of packaging this install. It makes this subject way more accessible. Docker was the right choice, and now we've smoothed off one of the rough edges.

BTW: Did you fix the instructions that get displayed in the terminal when you start up the notebook to mention port 9990 (not 8888)? Thanks again.

**Comment by DEKHTIARJonathan** [comment]
There is nothing to fix! It is running on port 8888... 
You should read again my previous post... 

The port running the app is 8888 so it's perfectly normal! How ever Docker map the port 9990 to this VM 's port 8888.

Bro, please have a look to Docker documentation... Getting bored of repeating the exact same things...

**Comment by richb-hanover** [comment]
Sorry, we're going to have to disagree. What the Docker instance displays when it starts is wrong:

````
$ docker run -i -p 9990:8888 -v $PWD:/neural-nets -t neural-nets-fun:caffe /bin/bash -c 'export PYTHONPATH=/opt/caffe/python && cd /neural-nets && ipython notebook --no-browser --ip 0.0.0.0'
[I 14:07:23.437 NotebookApp] Writing notebook server cookie secret to /.local/share/jupyter/runtime/notebook_cookie_secret
[I 14:07:23.497 NotebookApp] Serving notebooks from local directory: /neural-nets
[I 14:07:23.497 NotebookApp] 0 active kernels 
[I 14:07:23.497 NotebookApp] The IPython Notebook is running at: http://0.0.0.0:8888/
[I 14:07:23.497 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
````

It's wrong because browsing to the URL does **not** work, even on Linux. I realize that there are two fixes:

1. Change the URL in the second-to-last line to http://0.0.0.0:9990
2. Remove the port mapping by with the command ````docker run -i -p 8888:8888 ...````

Either works, but I think it's simpler to change the URL (alternative #1 above) because there's lots of documentation (especially the article on recurse.com) that would need to be updated.

**Comment by jvns** [comment]
> BTW: Did you fix the instructions that get displayed in the terminal when you start up the notebook to mention port 9990 (not 8888)? Thanks again.


Fixed: it should be less confusing now. Thanks for pointing out that this is confusing!

**Comment by richb-hanover** [comment]
Excellent! I did these steps to update the installation:

* I did ````git pull```` in the neural-nets-are-weird directory to pick up the new README.md.
* I then used the ````docker build ...```` command to rebuild (it ran really fast!) 

Running the ````docker run -i -p 9990:9990 ...```` then worked as expected. Thanks again.
