### ISSUE TITLE
size mismatch problem on ubuntu 14.04 

### ISSUE THREAD

**Issue by joshw0322** [jvns/neural-nets-are-weird#9]
I ran the docker build command
the outputs are as follows:

Get:230 http://http.debian.net/debian/ wheezy/main libraw1394-tools amd64 2.0.9-1 [38.4 kB]
Get:231 http://http.debian.net/debian/ wheezy/main libx11-doc all 2:1.5.0-1+deb7u2 [2609 kB]
Get:232 http://http.debian.net/debian/ wheezy/main manpages-dev all 3.44-1 [1737 kB]
Failed to fetch http://http.debian.net/debian/pool/main/libu/libunistring/libunistring0_0.9.3-5_amd64.deb  Size mismatch
Failed to fetch http://http.debian.net/debian/pool/main/x/x11proto-kb/x11proto-kb-dev_1.0.6-2_all.deb  Size mismatch
Fetched 113 MB in 6min 19s (299 kB/s)
Unable to correct missing packages.
E: Aborting install.
The command '/bin/sh -c apt-get -y --force-yes install libprotobuf-dev libleveldb-dev libsnappy-dev libopencv-dev libhdf5-serial-dev protobuf-compiler' returned a non-zero code: 100

-------------------------------------------------------------
I tried changing the source list of software installation. It didn't work, as the link shown above was still from debian.
I reinstalled ubuntu. I also tried adding --ignore-missing option into dockerfile, which failed as well.

If I may, I want to ask about the possible cause of and solution to this size mismatch problem. Thanks a lot!

**Comment by DEKHTIARJonathan** [comment]
You can try to use my automated builds : 

docker pull born2data/caffecv:http

Perfectly working ;)

**Comment by joshw0322** [comment]
I'm not sure whether i did it right

After I ran the docker pull command, I went on running the next line in readme:
root@joshw-virtual-machine:/home/joshw# docker run -i -p 9990:9990 -v $PWD:/neural-nets -t born2data/caffecv:http /bin/bash -c 'export PYTHONPATH=/opt/caffe/python && cd /neural-nets && ipython notebook --no-browser --ip 0.0.0.0 --port=9990'
(I just changed the name of image into born2data/caffecv:http)

When I hit http://localhost:9990/notebooks/notebooks/neural-nets-are-weird.ipynb,
a 404-not found page just turn out.

sorry to bother you with silly questions again...

**Comment by DEKHTIARJonathan** [comment]
The container launched correctly right ?

If so, I guess you tried to access the notebook outside your VM (joshw-virtual-machine).

So localhost is non-sense, try using the **VM's IP address** instead of **localhost**.

And btw. just try this : http://VM-IPaddress:9990/ No need for the supa long query.

**Comment by joshw0322** [comment]
Thanks! I ignored the message that
[I 05:06:28.530 NotebookApp] The IPython Notebook is running at: http://0.0.0.0:9990/
and this hyperlink worked.

Many thanks!
